/* Toutes les identités, offres, prix et vérifications ci-dessous sont fictifs. */
'use strict';
window.DRC_DATA = {
  categories: ['Agroalimentaire', 'Mode & textile', 'Artisanat & décoration', 'Services'],
  sellers: [
    {id:'kivu',name:'Coopérative des Collines',city:'Bukavu',category:'Agroalimentaire',about:'Exemple de coopérative de producteurs de café et de cacao. Une fiche professionnelle permet de présenter les lots, les méthodes de préparation et les capacités de production.',email:'contact@example.com',phone:'',verified:true},
    {id:'atelier',name:'Atelier Fleuve',city:'Kinshasa',category:'Mode & textile',about:'Exemple d’atelier de création textile et de décoration. Les collections peuvent être commandées en petite série ou adaptées aux besoins d’un acheteur professionnel.',email:'atelier@example.com',phone:'',verified:false},
    {id:'fibres',name:'Fibres du Kasaï',city:'Kananga',category:'Artisanat & décoration',about:'Exemple de collectif d’artisans travaillant les fibres végétales. Chaque fiche précise la matière, les dimensions et les possibilités de personnalisation.',email:'fibres@example.com',phone:'',verified:true},
    {id:'studio',name:'Studio Congo Créatif',city:'Lubumbashi',category:'Services',about:'Exemple de PME de services créatifs accompagnant les marques dans la conception de leur identité et de leurs supports numériques.',email:'studio@example.com',phone:'',verified:false}
  ],
  products: [
    {id:'cafe',seller:'kivu',name:'Café arabica des hauts plateaux',category:'Agroalimentaire',type:'Produit',price:12,unit:'kg',minimum:'10 kg',city:'Bukavu',art:'coffee',description:'Lot d’exemple de café arabica en grains. Profil aromatique, niveau de torréfaction, conditionnement et disponibilité à confirmer avec le producteur avant toute commande.',details:'Origine présentée : Sud-Kivu · Conditionnement illustratif : sachet de 1 kg · Échantillons à discuter.',active:true},
    {id:'panier',seller:'fibres',name:'Panier tressé en fibres naturelles',category:'Artisanat & décoration',type:'Produit',price:24,unit:'pièce',minimum:'5 pièces',city:'Kananga',art:'basket',description:'Panier artisanal d’exemple pour la décoration et le rangement. Les dimensions et les finitions peuvent varier selon la série et sont à préciser dans la demande.',details:'Matière illustrée : fibres végétales · Fabrication manuelle · Personnalisation sur demande.',active:true},
    {id:'textile',seller:'atelier',name:'Collection textile — Équateur',category:'Mode & textile',type:'Produit',price:18,unit:'mètre',minimum:'6 mètres',city:'Kinshasa',art:'textile',description:'Collection fictive de textiles à motifs géométriques. Demandez au vendeur les compositions, coloris, techniques de fabrication et délais disponibles.',details:'Motifs illustratifs · Vente au métrage · Séries limitées à confirmer.',active:true},
    {id:'cacao',seller:'kivu',name:'Fèves de cacao séchées',category:'Agroalimentaire',type:'Produit',price:8,unit:'kg',minimum:'25 kg',city:'Bukavu',art:'cocoa',description:'Offre fictive de fèves de cacao destinées aux acheteurs professionnels. Un échantillon, les caractéristiques du lot et les documents disponibles sont à demander au producteur.',details:'Conditionnement à convenir · Lot et origine à documenter · Contrôle qualité à organiser.',active:true},
    {id:'deco',seller:'fibres',name:'Suspension artisanale tressée',category:'Artisanat & décoration',type:'Produit',price:45,unit:'pièce',minimum:'3 pièces',city:'Kananga',art:'lamp',description:'Suspension décorative fictive en fibres tressées. Présentée comme abat-jour seul ; tout équipement électrique et ses exigences doivent être précisés séparément.',details:'Abat-jour décoratif · Dimensions à préciser · Emballage adapté à discuter.',active:true},
    {id:'design',seller:'studio',name:'Identité visuelle pour votre marque',category:'Services',type:'Service',price:null,unit:'projet',minimum:'1 projet',city:'Lubumbashi',art:'design',description:'Exemple de prestation de création de logo et de supports de communication. Le périmètre, les livrables, les droits d’utilisation et le calendrier sont fixés avec le prestataire.',details:'Service à distance · Devis personnalisé · Livrables et révisions à convenir.',active:true}
  ],
  partners: [
    {id:'ocean',name:'Partenaire maritime A',city:'Matadi',service:'Transport maritime',regions:['Europe','Afrique'],verified:true,description:'Fiche fictive pour tester une demande de fret maritime et de groupage. Aucune ligne, capacité ou habilitation réelle n’est attestée.'},
    {id:'air',name:'Partenaire aérien B',city:'Kinshasa',service:'Transport aérien',regions:['Europe','Afrique','Amérique','Asie'],verified:true,description:'Fiche fictive pour explorer l’envoi d’échantillons ou de petits lots par avion. Prix et disponibilité doivent être confirmés par un prestataire réel.'},
    {id:'formalites',name:'Agence d’accompagnement C',city:'Kinshasa',service:'Accompagnement export',regions:['Europe','Afrique','Amérique','Asie'],verified:true,description:'Fiche fictive d’accompagnement à la préparation d’un dossier export. Les documents dépendent du produit et du pays de destination.'},
    {id:'route',name:'Partenaire routier D',city:'Lubumbashi',service:'Transport routier',regions:['Afrique'],verified:false,description:'Fiche fictive de transport régional. Le statut en attente illustre le contrôle préalable d’un partenaire.'}
  ]
};
